language: scala

sudo: false

script:
  - sbt "++${TRAVIS_SCALA_VERSION}" "^^${SBT_VERSION}" test scripted

matrix:
  include:
  - env: SBT_VERSION="0.13.17"
    jdk: openjdk7
    scala: 2.10.7

  - env: SBT_VERSION="1.0.1"
    jdk: oraclejdk8
    scala: 2.12.3
