language: scala

sudo: false

script:
  - sbt "++${TRAVIS_SCALA_VERSION}" "^^${SBT_VERSION}" test scripted

matrix:
  include:
  - env: SBT_VERSION="0.13.16"
    jdk: openjdk7
    scala: 2.10.6

  - env: SBT_VERSION="1.1.0"
    jdk: oraclejdk8
    scala: 2.12.4

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
